### ISSUE TITLE
Lost configuration after migration from 1.2.X to 1.3.0

### ISSUE THREAD

**Issue by epoiseau** [volendavidov/NagBar#1]
Hi 

thanks for the tool that I use every day. This is great and I like it. When I have update from 1.2.4 to 1.3.0 I have lost of the configuration to the endpoint I have (I have many of them - 18 ) 

Apparently the new version is using a differ. Is there an easy way to use or transfer the data from the old version to the new ?

**Comment by volendavidov** [comment]
In short: No, unfortunately there is no easy way. Perhaps a bit more convenient way to get (copy the strings) the configuration is with the command `strings ~/Library/Preferences/com.volendavidov.NagBar.plist`.

Explanation:
The old configuration was stored with `NSKeyedArchiver` while the new one is stored in a Realm database. I had difficulties using `NSKeyedArchiver` with Swift (the app was originally written in Objective-C), so I decided to switch to Realm database. Besides the easier way of manipulating data, it is also possible to view and modify the database with Realm Browser. Since there was no easy way to continue to use `NSKeyedArchiver`, I wasn't able to make a piece that would transfer the preferences from `NSKeyedArchiver` to Realm.
